name: Build

on:
  push:
    branches: [main]

jobs:
  build-backend:
    name: Backend Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          tags: privmail-backend:latest

  build-frontend:
    name: Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/web
          push: false
          tags: privmail-frontend:latest
